language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: CloudMusicPlayer.xcodeproj #3
xcode_scheme: CloudMusicPlayer #4
xcode_sdk: iphonesimulator9.2 #5

before_install:
  - brew update
  - brew install carthage

before_script:
  - carthage update  