language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: CloudMusicPlayer.xcodeproj #3
xcode_scheme: CloudMusicPlayer #4
xcode_sdk: iphonesimulator9.2 #5

env:
  global:
  #- WORKSPACE=
  - PROJECT=CloudMusicPlayer.xcodeproj
  - FRAMEWORK_SCHEME=CloudMusicPlayer
  - SDK=iphonesimulator9.2

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
- xcodebuild -scheme "$FRAMEWORK_SCHEME" -project "$PROJECT" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' test -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES  | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash)