language: objective-c
osx_image: xcode7.3
xcode_project: CloudMusicPlayer.xcodeproj

env:
  global:
  #- WORKSPACE=
  - PROJECT=CloudMusicPlayer.xcodeproj
  - FRAMEWORK_SCHEME=CloudMusicPlayer
  - SDK=iphonesimulator9.3
  - DESTINATION_PLATFORM='platform=iOS Simulator,name=iPhone 6,OS=9.3'

before_script:
- carthage bootstrap --platform ios

script: 
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -scheme "$FRAMEWORK_SCHEME" -project "$PROJECT" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=YES -destination "$DESTINATION_PLATFORM" test -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES  | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash)