language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: CloudMusicPlayer.xcodeproj #3
xcode_scheme: CloudMusicPlayer #4
xcode_sdk: iphonesimulator9.2 #5
script: 
  - xctool -project loudMusicPlayer.xcodeproj -scheme CloudMusicPlayer build test -sdk iphonesimulator9.2 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)