language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: CloudMusicPlayer.xcodeproj #3
xcode_scheme: CloudMusicPlayer #4
xcode_sdk: iphonesimulator9.2 #5
script: 
- xcodebuild -scheme CloudMusicPlayer -project CloudMusicPlayer.xcodeproj -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' build test -enableCodeCoverage YES"
after_success:
  - bash <(curl -s https://codecov.io/bash)